---
title: Count and cluster colors for route {{ from }} to {{ to }} 
output: github_document
---

```{r setup}
library(tidyverse)
library(colorspace)
library(routes)
library(here)
set.seed(21978) # both subsampling and clustering are random, 
                # set a seed to get reproducible image
```


## Read in Streetview image manfest

```{r}
route_images <- read_rds(here("{{{ shortname }}}", "images", "manifest.rds"))
```

## Get sample of pixels from images

Sample 50 pixels from each image:
```{r}
pixel_sample_rgb <- route_images %>% 
  pull(image) %>% 
  map_dfr(sample_pixels, sample_size = 50) %>% 
  with(RGB(R, G, B)) 
```

## Create cluster centers
```{r}
cluster_space <- "LUV"
n_clusters <- 50
```

Clustering done in `r cluster_space` color space, with `r n_clusters` clusters:
```{r}
pixel_sample_space <- pixel_sample_rgb %>% 
  as(cluster_space)

clusters <- kmeans(pixel_sample_space@coords, centers = n_clusters)
centers <- match.fun(cluster_space)(clusters$center)

centers %>% hex() %>% pal()
```

## Count pixels in each cluster

```{r}
color_freq_sample <- count_colours(pixel_sample_rgb, centers,
  colorspace = cluster_space)
```

Histogram of counts based on sample:
```{r}
color_freq_sample %>% 
  ggplot(aes(hex, freq, fill = hex)) +
    geom_col() +
  scale_fill_identity() +
  coord_flip()
```

## Count pixels in each image

```{r}
route_images <- route_images %>% 
  mutate(
    pixels = map(image, read_pixels) %>% map(RGB),
    color_count = map(pixels, count_colours, 
      centers = centers, colorspace = cluster_space))
```

## Plot

Depending on color space try reordering by one of the dimensions:
```{r, fig.width = 10, fig.height = 3}
route_images %>% 
  unnest(color_count) %>% 
  ggplot(aes(order, freq)) +
    geom_area(aes(fill = hex)) +
  scale_fill_identity() +
  theme_void()
```

```{r}
ggsave(here("{{{ shortname }}}", "{{{ shortname }}}_route.jpeg"), 
  height = 3, width = 10, dpi = 1800/10)
```

